Fix value param in Javadoc of addParamToMultipart (#24931)
This bug causes the `javadoc` tool to fail for the generated code with:

```
error: @param argument "obj" is not a parameter name.
   * @param obj Object
```