Replace #import with #include in the Qt5 generator
The SWGHelpers.cpp file uses non-standard #import statements. This
causes the following error when built using Visual Studio 2013:

SWGHelpers.cpp(4): fatal error C1083: Cannot open type library file:
'c:\qt\qt5.5.1\5.5\msvc2013_64\include\qtcore\qdebug': Error loading
type library/DLL.