Fix typescript codegen crash on extracting regular expression
Fixes codegen returns error when schema has a pattern property:

```
Exception: Unbalanced '{' - missing '}' at
'z0-9]{3'
```